branches:
  only:
    - master
    - "/^v[0-9.]+/"


environment:

   matrix:

      - PYTHON_VERSION: 3.7
        MINICONDA: C:\Miniconda37-x64
        PYDIST: 37
        MINGWDIR: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64

init:
   - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
    - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
    - "set PATH=%MINGWDIR%;%MINGWDIR%\\bin;%PATH%"
    - "set C_INCLUDE_PATH=%MINGWDIR%\\include;%MINGWDIR%\\lib\\gcc\\x86_64-w64-mingw32\\6.3.0\\include"
    #- "cd C:\\mingw-w64\\x86_64-6.3.0-posix-seh-rt_v5-rev1\\mingw64"
    #- "dir"
    #- "cd include"
    #- "dir"
    - "conda config --set always_yes yes --set changeps1 no"
    - "conda update -q conda"
    - "conda create -q -n test-environment python=%PYTHON_VERSION%"
    - "activate test-environment"
    - "cd C:\\projects\\amfe-2tyct"
    - "python conda_setup.py"
    - "cd %MINICONDA%\\envs\\test-environment\\Lib"
    - "dir"
    - "cd C:\\projects"
    - "dir"
    - "cd C:\\projects\\amfe-2tyct\\AppVeyor"
    - "copy /Y distutils.cfg %MINICONDA%\\envs\\test-environment\\Lib\\distutils\\distutils.cfg"
    - "copy /Y cygwinccompiler.py %MINICONDA%\\envs\\test-environment\\Lib\\distutils\\cygwinccompiler.py"
    - "copy /Y mingw32ccompiler.py %MINICONDA%\\envs\\test-environment\\Lib\\site-packages\\numpy\\distutils\\mingw32ccompiler.py"
    - "cd .."
    - "python setup_develop.py develop no_feti"

build: off

test_script:
  - "nosetests"
