# The idea of this CI tool should be to run nosetest for unit tests and
# additionally to that some test cases using dynamic and static stuff.
#

stages:
    - build
    - unittest
    - doctest
    - modeltest
    - linttest

build_code:
    stage: build
    script:
        - export PATH="/home/gitlab-runner/anaconda3/bin:$PATH"
        - python setup.py develop

unittest:
  stage: unittest
  script:
    - export PATH="/home/gitlab-runner/anaconda3/bin:$PATH"
    - nosetests

physical_test:
    stage: modeltest
    script:
        - export PATH="/home/gitlab-runner/anaconda3/bin:$PATH"
        - python setup.py develop
        - cd tests
        - python run_mechanical_system.py
        - python run_mesh.py

documentation_test:
    stage: doctest
    script:
        - export PATH="/home/gitlab-runner/anaconda3/bin:$PATH"
        - python setup.py build_sphinx

language_quality_test:
    stage: linttest
    script:
        - pylint amfe
