language: python

matrix:
   include:
      - os: linux
        python: 3.7
        env:
          - PYCONDA=3.7
          - PYDIST=37

branches:
  only:
  - master
  - "/^v[0-9.]+/"

before_install:
- "sudo apt-get install gfortran"
#- "sudo apt-get install libhdf5-serial-dev"
- "wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh"
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- export NPY_DISTUTILS_APPEND_FLAGS=1
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a

install:
   - "conda create -q -n test-environment python=${PYCONDA} python=3.7"
   - "source activate test-environment"
   - "python conda_setup.py"
   - "python setup_develop.py develop no_feti"

script:
   - "nosetests"
   - "cd docs"
   - "make html"
   - "cd .."
